### ISSUE TITLE
Cargo workspaces interfere with cargo raze

### ISSUE THREAD

**Issue by IronPeak** [google/cargo-raze#111]
I have cargo workspaces setup in my project for the `rust rls` extension in vscode along side Bazel.

If I try to follow the setup instructions for vendoring I get:

```
Loaded override settings: RazeSettings {
    workspace_path: "//cargo",
    target: "x86_64-unknown-linux-gnu",
    crates: {},
    gen_workspace_prefix: "raze",
    genmode: Vendored,
    output_buildfile_suffix: "BUILD.bazel",
}
error: Raze failed to render with cause: "Failed to find expected vendored crates in Some("/home/ironpeak/Projects/dungeon-core/cargo/./vendor/"): ["logical-0.1.0", "engine-0.1.0", "entities-0.1.0", "parser-0.1.0", "arithmetic-0.1.0"] and 3 others. Did you forget to run cargo-vendor?"
```

I have found that I can successfully run `cargo raze` if I delete the `Cargo.toml` workspace and follow the instructions.

**Comment by acmcarther** [comment]
I see. The right behavior here is probably to ignore those workspace crates. It looks like the list of workspace crates is available in `metadata.workspace_members`. I'll add this and prune these from the vendor check.

Thanks for reporting, I'll update this issue when it's fixed.

**Comment by acmcarther** [comment]
Oh, I should add one more thing.

cargo-raze doesn't currently generate a BUILD file for workspace crates. It's not difficult to add this if there are opinions about where these files should be generated to.

**Comment by acmcarther** [comment]
This is in 0.2.10.

I suspect there may be other issues or missing features with workspace crates. Please feel free to reopen or open another issue and I'll take a look.

**Comment by samschlegel** [comment]
This has regressed with https://github.com/google/cargo-raze/pull/150
