### ISSUE TITLE
Fails to build actix-http with "use of undeclared type or module fail_ure"

### ISSUE THREAD

**Issue by a1ph** [google/cargo-raze#125]
I'm getting the following error:

error[E0433]: failed to resolve: use of undeclared type or module fail_ure
--> external/raze__actix_http__1_0_1/src/error.rs:968:24
|
968 | impl ResponseError for fail_ure::Error {}
| ^^^^^^^^ use of undeclared type or module fail_ure

error: aborting due to previous error

Is there a way to work around it?

**Comment by KaiserKarel** [comment]
This looks like you have a typo in your cargo.toml, since you are using the [failure](https://github.com/rust-lang-nursery/failure) crate I suppose?

**Comment by Arm1stice** [comment]
This issues is the same as #143 and should be fixed by #162
