### ISSUE TITLE
Cargo environment variables

### ISSUE THREAD

**Issue by KaiserKarel** [google/cargo-raze#138]
Is there a way to get build.rs, which use env variables such as `CARGO_CFG_TARGET_OS` to work?

**Comment by GregBowyer** [comment]
Not presently but maybe.

One option would be to make a patch if we land #121 
Or it might be one of the env options we should add to rules-rust

**Comment by KaiserKarel** [comment]
That has landed already correct? Where can I read more on the patches functionality?

**Comment by GregBowyer** [comment]
I should write up some docs, but the long and the short is its just exposing the patch parts of workspace rules like so

https://docs.bazel.build/versions/master/repo/git.html

**Comment by KaiserKarel** [comment]
I think that should work; are these git generated patch files?  Or where can I read more on bazel's patcher?

**Comment by Sythanis** [comment]
Have the same difficulty. Trying with a git generated 
```
From 0664dd57eca5981090962953834e118ace670e58 Mon Sep 17 00:00:00 2001
From: ... <...>
Date: Sun, 8 Mar 2020 09:29:29 -0400
Subject: [PATCH 1/1] Patched TypeNum for Bazel

---
 src/lib.rs | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/lib.rs b/src/lib.rs
index 2972c57..c37f74c 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -62,8 +62,8 @@
 
 use core::cmp::Ordering;
 
-include!(env!("TYPENUM_BUILD_OP"));
-include!(env!("TYPENUM_BUILD_CONSTS"));
+include!(concat!(env!("OUT_DIR"), "/consts.rs"));
+include!(concat!(env!("OUT_DIR"), "/op.rs"));
 
 pub mod bit;
 pub mod int;
-- 
2.20.1

```

**Comment by KaiserKarel** [comment]
So if I read the source correctly; the patch functionality is only applied to Remote crates. Using the following config did the trick for me: 

I used the unix diff for generating the patches.
```patch.diff
+++ src/src/lib.rs	2020-03-06 14:48:46.082759174 +0100
@@ -62,8 +62,8 @@
 
 use core::cmp::Ordering;
 
-include!(env!("TYPENUM_BUILD_OP"));
-include!(env!("TYPENUM_BUILD_CONSTS"));
+include!(concat!(env!("OUT_DIR"), "/consts.rs"));
+include!(concat!(env!("OUT_DIR"), "/op.rs"));
 
 pub mod bit;
 pub mod int;
```

```Cargo.toml
[raze.crates.typenum.'1.11.2']
gen_buildrs = true
patches = ["//cargo/patch/typenum-1.11.2:include_env.diff"]
patch_args = ["-p1"]
```

**Comment by TheButlah** [comment]
FWIW using the `force_unix_path_separator` feature for typenum makes this unecessary now

**Comment by TotempaaltJ** [comment]
This is what I used to fix it specifically:

```toml
[raze.crates.typenum.'1.12.0']
gen_buildrs = true
additional_flags = [
    "--cfg=feature=\\\"force_unix_path_separator\\\"",
]
```
