### ISSUE TITLE
Can I have two different versions of the same Rust library in one Bazel project?

### ISSUE THREAD

**Issue by DmitryRusakovKodiak** [google/cargo-raze#144]
Hi! Can I have two different versions of the same Rust library in one Bazel project?
For example, some projects within one Bazel repository can depend on `futures-0.1.x`, but some can require `futures-0.3.x`. How to handle such use case using cargo-raze?

**Comment by dnrusakov** [comment]
cc @acmcarther

**Comment by acmcarther** [comment]
cargo-raze doesn't have a good story for this for now. If cargo itself has one, I think we could probably tweak raze to provide access to these types of dependencies.

Is there syntax in cargo for including multiple versions of the same dep? We currently do pull multiple versions of the same dep for dependency resolution, but up until now there wasn't a case made for providing workspace-visible aliases to them.

For now, you might be able to address this in limited situations by having a second raze directory, but that would probably duplicate many other dependencies and could result in having multiple incompatible versions of the same types.

**Comment by GregBowyer** [comment]
Aliases do this and I should work on getting it merged

**Comment by dnrusakov** [comment]
> Aliases do this and I should work on getting it merged

@GregBowyer Yes, please!

**Comment by GregBowyer** [comment]
#187 should do this for you

**Comment by dnrusakov** [comment]
@GregBowyer Thanks a lot! Hopefully your PR will be merged soon!
