### ISSUE TITLE
Feature request: Utilize cargo_metadata for parsing Cargo metadata

### ISSUE THREAD

**Issue by smklein** [google/cargo-raze#147]
See title: https://docs.rs/cargo_metadata/0.9.1/cargo_metadata/index.html

I think this crate could be used for parsing metadata from cargo, instead of relying on a hand-rolled implementation in impl/src/metadata.rs.

Hopefully this would make tracking upstream Cargo changes slightly easier to follow?

What do ya'll think? Would this be a welcome change?

**Comment by acmcarther** [comment]
Yeah, this sounds good to me. Duplicating cargo's structs as we're doing now isn't great.

I'll look into this this upcoming weekend, or feel free to take this. I think we use an interface for metadata fetching, so it should be reasonably low effort to drop in a cargo-metadata wrapped implementation (or just drop the abstraction entirely).

**Comment by acmcarther** [comment]
Oh, I lied.

We actually already do this, and I think we recently flipped the default to use cargo-metadata. Here is the type:

https://github.com/google/cargo-raze/blob/7daf5ba22612b5807492aa568c2a7b71c8630d4e/impl/src/metadata.rs#L162-L165

I'm guessing your ask here is that we remove the old implementation. I'm not averse to this.
