### ISSUE TITLE
Includes from source directories via include_str break builds

### ISSUE THREAD

**Issue by palfrey** [google/cargo-raze#15]
I've got some code that depends on [conduit-mime-types](https://github.com/conduit-rust/mime-types) and it uses `include_str!` to [include an external data file at build time](https://github.com/conduit-rust/mime-types/blob/master/src/lib.rs#L10). However, this doesn't seem to play nicely with the current generated rules.

I managed to make it work by adding a `data = ["data/mime.json"]` line to the generated `rust_library` but I don't think there's currently any way to add that via the Cargo.toml flags?

**Comment by mfarrugi** [comment]
This was recently fixed with #10, coincidentally for the same library (https://github.com/acmcarther/cargo-raze-examples/pull/3/files#diff-24a61fcd02e164299430b7286ed18fbaR37).

It doesn't appear to be released yet, though.

**Comment by acmcarther** [comment]
Released as `0.0.19`, plus updated example: https://github.com/acmcarther/cargo-raze-examples/blob/5ab156b9d93a6a2760c7d34922116c4c7bb43b91/bazel/complicated_cargo_library/cargo/Cargo.toml#L36

**Comment by palfrey** [comment]
Yup, this is fixed with 0.0.19
