### ISSUE TITLE
buildrs_additional_environment_variables is no longer respected after #166

### ISSUE THREAD

**Issue by dayfine** [google/cargo-raze#179]
After #166, `buildrs_additional_environment_variables` is no longer respected. An example breakage is that `rust-protobuf` can no longer be built, as its [`build.rs`](https://github.com/stepancheg/rust-protobuf/blob/master/protobuf/build.rs) expected `RUSTC` and `CARGO_PKG_VERSION`. I temporarily unblocked myself by downgrading from 0.3.5 to 0.3.3, but I think the `buildrs_additional_environment_variables` should keep being supported, or it should be removed with its replacement documented.

**Comment by damienmg** [comment]
#166 should pass along `RUSTC` and `CARGO_PKG_VERSION`, can we have a repro?

Also I ran in a couple of different problems with latest version of cargo raze that could be related, cf: https://github.com/google/cargo-raze/issues/177

**Comment by dayfine** [comment]
It passes `RUSTC` along (by means other than `buildrs_additional_environment_variables`), but not `CARGO_PKG_VERSION`.

I am building rust-protobuf in this repo by relying on `buildrs_additional_environment_variables` and some other magic: https://github.com/dayfine/xlab/blob/master/third_party/cargo/Cargo.toml. IIRC:
- If I use `0.3.4` and above, it will first complain the `rustc` magic I put in is not a rust_library or cc_library
- Then after removing the rustc magic, `CARGO_PKG_VERSION` is still not properly passed, i.e. the `buildrs_additional_environment_variables` is not in the generated BUILD file. I've tried to use `additonal_flags` or `additional_envs`, which will show up in `buildrs_additional_environment_variables`, but with `gen_buildrs = true`, the build invocation does not actually pass `CARGO_PKG_VERSION` and the package still complain about missing `CARGO_PKG_VERSION`

**Comment by damienmg** [comment]
Indeed the CARGO_PKG_VERSION is not added, let me try to send a PR to fix that on rules_rust.

**Comment by dayfine** [comment]
Thanks, and it will also need to be passed in the template: https://github.com/google/cargo-raze/blob/master/impl/src/templates/partials/build_script.template?

**Comment by damienmg** [comment]
Yes :) #180 was already on my computer yesterday but now it is sent for review :)

**Comment by dayfine** [comment]
Hi Damien, could a new release be cut so I can install the new version and verify this change? Thanks!

**Comment by acmcarther** [comment]
Published [0.3.7](https://crates.io/crates/cargo-raze/0.3.7) containing this fix.
