### ISSUE TITLE
Support generating rust-analyzer `rust-project.json`

### ISSUE THREAD

**Issue by aignas** [google/cargo-raze#186]
Rust-analyzer supports non-cargo based projects.

It would be interesting to do the generation of the `rust-project.json` at the root of the repository, such that `rust-analyzer` could refer to dependencies managed by `cargo-raze`.

I'm not sure if this is a feature request to rules_rust and/or cargo-raze. In my view they are somewhat related, but I am not sure about the current state of the project.

Docs: https://rust-analyzer.github.io/manual.html#non-cargo-based-projects

**Comment by GregBowyer** [comment]
Humm interesting, this might be better on rules_rust as a target or aspect
