### ISSUE TITLE
DEBUG: A canonical reproducible form can be obtained by modifying arguments sha256 = ...

### ISSUE THREAD

**Issue by UebelAndre** [google/cargo-raze#188]
Would it be possible for `cargo raze` to be able to generate the `_new_http_archive` targets and populate the `sha` argument? Is that something in the metadata for the crates?

The snippet below is some output I get when running `bazel build //...` after running `cargo raze` on my project.
```output
DEBUG: Rule 'raze__ansi_term__0_11_0' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "ee49baf6cb617b853aa8d93bf420db2383fab46d314482ca2803b40d5fde979b"
DEBUG: Repository raze__ansi_term__0_11_0 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_user/0cfcbb78df5cbf7b031db3a300ee9e3b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'raze__strsim__0_8_0' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "8ea5119cdb4c55b55d432abb513a0429384878c15dde60cc77b1c99de1a95a6a"
DEBUG: Repository raze__strsim__0_8_0 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_user/0cfcbb78df5cbf7b031db3a300ee9e3b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'raze__bitflags__1_2_1' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "cf1de2fe8c75bc145a2f577add951f8134889b4795d47466a54a5c846d691693"
DEBUG: Repository raze__bitflags__1_2_1 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_user/0cfcbb78df5cbf7b031db3a300ee9e3b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
DEBUG: Rule 'raze__vec_map__0_8_2' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "f1bddf1187be692e79c5ffeab891132dfb0f236ed36a43c7ed39f1165ee20191"
```

**Comment by dfreese** [comment]
Which version of cargo raze was used?

I forget exactly which version this was updated in, but I do see the sha's filled out in 0.3.7 with the project I am working on.

**Comment by UebelAndre** [comment]
I actually see the same. And I'm using 0.37 as well. I'll dig deeper when I get a chance

**Comment by UebelAndre** [comment]
@dfreese Hey! Sorry it took me so long to get back to this. If you run `smoke-test.sh` on f77ba882ea4a7bd60b8a2761ec23b88bf6753c5f (which is `0.3.8`) then you'll see this issue in some of the Bazel builds.

I've attached a log for convenience.
[smoke-test.log](https://github.com/google/cargo-raze/files/5011270/smoke-test.log)

**Comment by UebelAndre** [comment]
This turned out to be because I was using [cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html). When you use cargo workspaces, your lockfile is generated at the workspace root. This leaves dangling lockfiles in your workspace if you were to have added the use of cargo workspace to your project after already setting up one package. After some time, you'll start to see missing SHAs as you update crates.

From here on this issue should be tracked in #262 so I'll close this
