### ISSUE TITLE
Create BUILD.bazel files instead of BUILD files for packages (possibly make it optional)

### ISSUE THREAD

**Issue by yesudeep** [google/cargo-raze#189]
Running cargo-raze currently generates `BUILD` files in the cargo and remote directories.
However, because the name `BUILD` can conflict with a directory named 'build' on case-insensitive
file systems, it's a much better idea to use the .bazel extension instead.

Related issue:
`cargo-raze` generates `BUILD` files in directories that already have a `BUILD.bazel` file as well.

Could you please make it optional to generate `BUILD.bazel` files instead of `BUILD` files perhaps via
a command line flag to set the extension?

**Comment by mstg** [comment]
Hello!
This is already supported (#93) 

Add `output_buildfile_suffix = "BUILD.bazel"` under `[raze]` in `Cargo.toml`

**Comment by yesudeep** [comment]
Thank you. That works!

This bug still exists however:

"cargo-raze generates BUILD files in directories that already have a BUILD.bazel file."

**Comment by UebelAndre** [comment]
Hey @yesudeep, 

I opened #205 to update the default buildfile suffix.

Additionally, If you build using `incompatible_relative_workspace_path = True` and run `cargo-raze` within a Bazel workspace, raze will treat `workspace_path` as a Bazel label and put the generated files in the specified directory. This should avoid any conflicts you might have seen before.

**Comment by UebelAndre** [comment]
@yesudeep does #205 satisfy this issue?

**Comment by UebelAndre** [comment]
If it does, could you close the ticket?

**Comment by yesudeep** [comment]
Hey @UebelAndre thank you! :-)
