### ISSUE TITLE
Be a subprocess under Gazelle?

### ISSUE THREAD

**Issue by alexeagle** [google/cargo-raze#195]
In rules_nodejs and rules_python we are thinking about BUILD file generation, and would like to use Gazelle to drive it. However we don't want to write all our stuff in Go. This isn't just out of vanity; we need to use libraries like the TypeScript compiler so we need to write plugins that run in nodejs.

After discussion with @achew22 we are thinking of contributing a layer to gazelle where it would invoke a subprocess for each Language interface, then use some sort of proto/JSON-over-stdio.

Maybe this would be interesting for you as well, to write a Rust program that could be controlled by gazelle? If so maybe we can collaborate on the Go layer that could live in gazelle.

**Comment by UebelAndre** [comment]
Hey, maybe there have been other conversations about this but from an outsider's perspective, this seems like something the code owners of [rules_rust](https://github.com/bazelbuild/rules_rust) would also be interested in. Might be worth pinging them here too if no other conversations have taken place already 😅

**Comment by UebelAndre** [comment]
@acmcarther expressed interest in using Bazel-Gazelle in one of my PRs before. Perhaps you two could connect and discuss this?

**Comment by alexeagle** [comment]
We should get @jayconrod input on it. I should file this on the gazelle repo as an RFC

**Comment by alexeagle** [comment]
let's just follow-up on https://github.com/bazelbuild/bazel-gazelle/issues/938
