### ISSUE TITLE
Request: Mark files generated by raze with a @generated signature

### ISSUE THREAD

**Issue by andydau212** [google/cargo-raze#196]
We want to be able to skip formatting checks for generated files as well as preventing people from being able to edit these files directly.

Anyone opposed to adding a feature to add a predetermined signature (like @generated) to the BUILD files created by cargo raze?

**Comment by dfreese** [comment]
I'd be supportive of that sort of change.

While, it would be nice to have the auto-generated files match buildifier conventions, that's a bigger change given the use of templates currently.

**Comment by andydau212** [comment]
Sounds good. I can tackle this once I got some free time. Would there be any reasons people might not want this? I can add it as optional feature flag in raze config if so. I can't think of any reason why this would be an issue tho so maybe just adding it straight to the template is fine?

**Comment by dfreese** [comment]
Closed by #197.

**Comment by PiotrSikora** [comment]
Files generated by `cargo raze` already contain `DO NOT EDIT! Replaced on runs of cargo-raze` in the header. What's the point of adding another marker 2 lines above? `@generated` doesn't seem to be any standard, and if anything, `DO NOT EDIT!` seems to be a more popular marker, including in files generated with `go generate`.
