### ISSUE TITLE
Cargo raze fails if build folder exists on macos

### ISSUE THREAD

**Issue by parisholley** [google/cargo-raze#208]
`Error: Is a directory (os error 21)`

I have a few dependencies (zmq, openssl, etc) that have a "build" folder when vendored, even though I am using them against already installed system libraries. the cargo raze command should remove these folders (with warnings?) automatically or perhaps use a different output, eg: BUILD.bazel

right now, i am setting `output_buildfile_suffix = "BUILD.bazel" to work around this

update: remove is not a good option, as some crates (like typenum) still require the build folder

**Comment by UebelAndre** [comment]
Yeah, while I haven't run into your particular situation, I've seen this come up in many others. I opened #205 to hopefully avoid most of these issues. I just need to clean up that branch but am waiting for #207 to go through first.

**Comment by UebelAndre** [comment]
@parisholley Does #205 satisfy your issue?

**Comment by UebelAndre** [comment]
@parisholley If it does, could you close the issue? 🙏

**Comment by parisholley** [comment]
yep
