### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by UebelAndre** [google/cargo-raze#216]
What's the process for doing releases for `cargo raze`? I think there's been a bunch of nice changes that have gotten in and would like to be able to use them without cloning and building the project locally. I think it'd be awesome if a release could be made following the merge of #212

**Comment by acmcarther** [comment]
Yo, undead maintainer here again.

This project never automated releases and I got real real lazy. I've helped bring some other folks up to speed on the release procedure, but the release process is pretty garbage, and so I understand why they've not be super proactive about it.

I was really going to write a script to do this last time I explained it, but I couldn't come up with a quick hack to up the version automatically. I now have the insight that theres not a good reason to want to do this automatically.

I built a thing and used it to published 0.5.0 (to reflect the large amount of recent changes). It is [available here](https://crates.io/crates/cargo-raze). I also sent out https://github.com/google/cargo-raze/pull/217 for review. I actually intended for you to review it, but I guess only whitelisted people can review, so I tagged Damien.

**Comment by UebelAndre** [comment]
@acmcarther Thank you!!! Yeah, there's a lot here. #212 is also a big one... I wonder what the release number should be for that one.

Regardless, #217 seems awesome and makes me happy as a fan of this project 😄 Thanks for being undead!

**Comment by UebelAndre** [comment]
I think once #217 is merged this issue can be closed

**Comment by acmcarther** [comment]
Closing, per https://github.com/google/cargo-raze/issues/216#issuecomment-693665029
