### ISSUE TITLE
Add sha256 pinning to http_archive macros

### ISSUE THREAD

**Issue by htuch** [google/cargo-raze#249]
The Envoy project now makes use of cargo-raze generated BUILD and we generally require that our external deps consumed via `http_archive` have `sha256` entries in the manifest. Can support for this be added to `cargo-raze`?

Tracked Envoy-side in https://github.com/envoyproxy/envoy/issues/13564

**Comment by UebelAndre** [comment]
@htuch There is already support for this. Run `cargo generate-lockfile` in the directories where you have your `Cargo.toml` files adn then re-run `cargo-raze`. This should generate the `sha256`s for you.

**Comment by htuch** [comment]
Thanks @UebelAndre. Will try this out at our end, closing out for now.
