### ISSUE TITLE
RFC: Documentation style

### ISSUE THREAD

**Issue by UebelAndre** [google/cargo-raze#299]
I'd really like to be able to use `rustdoc` to generate documentation but the current documentation style is not compatible. I'm wondering if this is a Google standard or if it can be updated to support `rustdoc`.

The following 
```rust
/** Determines if the target matches those supported by and defined in rules_rust
 *
 * Examples can be seen below:
 *
 * | target                                | returns          | reason                                           |
 * | ------------------------------------- | ---------------- | ------------------------------------------------ |
 * | `cfg(not(fuchsia))`                   | `(true, true)`   | `fuchsia` would be considered a 'default'        |
 * |                                       |                  | dependency since no supported target maps to it. |
 * |                                       |                  |                                                  |
 * | `cfg(unix)`                           | `(true, false)`  | There are supported platforms from the `unix`    |
 * |                                       |                  | `target_family` but not all platforms are of     |
 * |                                       |                  | the `unix` family.                               |
 * |                                       |                  |                                                  |
 * | `cfg(not(windows))`                   | `(true, false)`  | There are supported platforms in addition to     |
 * |                                       |                  | those in the `windows` `target_family`           |
 * |                                       |                  |                                                  |
 * | `x86_64-apple-darwin`                 | `(true, false)`  | This is a supported target triple but obviously  |
 * |                                       |                  | won't match with other triples.                  |
 * |                                       |                  |                                                  |
 * | `unknown-unknown-unknown`             | `(false, false)` | This will not match any triple.                  |
 * |                                       |                  |                                                  |
 * | `cfg(foo)`                            | `(false, false)` | `foo` is not a strongly defined cfg value.       |
 * | `cfg(target_os = "redox")`            | `(false, false)` | `redox` is not a supported platform.             |
 */
pub fn is_bazel_supported_platform(target: &str) -> (bool, bool) {
```
results in the following rendering:
![Screen Shot 2020-11-22 at 6 20 47 PM](https://user-images.githubusercontent.com/26427366/99924989-2128e200-2cf1-11eb-9578-693bff1224f9.png)

When what I had intended was:
![Screen Shot 2020-11-22 at 6 31 55 PM](https://user-images.githubusercontent.com/26427366/99924995-29811d00-2cf1-11eb-84f7-e5568415f972.png)

This just points out an incompatibility between the styles but I do feel it's incredibly useful to browse around docs to see what's got info and what doesn't to help track down missing information.

![Screen Shot 2020-11-22 at 6 40 07 PM](https://user-images.githubusercontent.com/26427366/99925249-3b16f480-2cf2-11eb-8980-f51de3cde585.png)

Is there any aversion to updating the docs from
```rust
/** Some header
 *
 * some details
 */
```
to
```rust
/// Some header
/// 
/// some details
```

**Comment by chansuke** [comment]
I don't feel any aversion to following official documentation [convention](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text) and I agree with the usefulness of that.

**Comment by acmcarther** [comment]
I'm fine with this change. I respect the value of consistency with the community. Most of the inconsistent style choices here date back to ancient times where they had no consequence.

(I do think this style "looks bad" though. Not looking forward to having to type "///" a bunch of times if my editor isn't smart enough to do it for me. I'm sad to have fallen on the losing side of so many of these "arbitrary" choices.)

**Comment by acmcarther** [comment]
Oh, and yeah, this isn't "google style", this is an abomination of style somewhat similar to [Google Java Style](https://google.github.io/styleguide/javaguide.html) and [Google C++ Style](https://google.github.io/styleguide/cppguide.html). Internal Rust (wherever it may or may not exist) almost certainly follows rust standard style to the letter.
