### ISSUE TITLE
Parse the Cargo.toml "links" attribute and include it in the generated templates

### ISSUE THREAD

**Issue by sitaktif** [google/cargo-raze#344]
This is an extension of #281 which involves parsing the [links](https://doc.rust-lang.org/cargo/reference/manifest.html#the-links-field) attribute from the Cargo.toml of crates that have it set and to cascade it to the generated BUILD files.

A workaround is to manually set the `links` attribute when needed, as described in https://github.com/bazelbuild/rules_rust/pull/549#discussion_r555146547.

**Comment by illicitonion** [comment]
This was done in https://github.com/google/cargo-raze/pull/400
