### ISSUE TITLE
`cargo package` includes examples/ and smoke_test/

### ISSUE THREAD

**Issue by acmcarther** [google/cargo-raze#36]
We should nest the crate source and `Cargo.*` files under a directory (`impl` is my current preference) so that `cargo package` doesn't include them in the packaged `crate` file.

cc: @bspeice

**Comment by acmcarther** [comment]
This is what I did:

```
$ cargo package
$ mkdir /tmp/unpack-crate
$ cd /tmp/unpack-crate 
$ tar -xzf ~/git/cargo-raze/target/package/cargo-raze-0.0.20.crate
$ ls examples
```

For some reason, the `cargo` directory isn't in the `examples/vendored/complicated_cargo_library` -- I currently suspect that cargo has some sort of hacky file filtering.

**Comment by bspeice** [comment]
Solution similar to how `futures` currently has a cargo workspace setup? https://github.com/rust-lang-nursery/futures-rs/blob/master/Cargo.toml

**Comment by bspeice** [comment]
So, I thought this was going to be straight-forward - move the implementation to a new directory, set up a Cargo.toml workspace, and call it a day.

Turns out it's not quite so nice:

```
error: current package believes it's in a workspace when it's not:
current:   /home/bspeice/Development/cargo-raze/examples/vendored/hello_cargo_library/cargo/Cargo.toml
workspace: /home/bspeice/Development/cargo-raze/Cargo.toml

this may be fixable by adding `examples/vendored/hello_cargo_library/cargo` to the `workspace.members` array of the manifest located at: /home/bspeice/Development/cargo-raze/Cargo.toml
```

If you don't distribute a root-level `Cargo.toml` everything still works out, but you lose the ability to `git clone; cd repo; cargo build`.

**Comment by bspeice** [comment]
@acmcarther - I don't have the ability to close this issue since I didn't create, can you mark it done?

**Comment by acmcarther** [comment]
Done
