### ISSUE TITLE
bytes-1.0.1 failed to build

### ISSUE THREAD

**Issue by tschuett** [google/cargo-raze#376]
cargo/vendor/bytes-1.0.1/BUILD.bazel:39:13: in @rules_rust//proto:proto.bzl%_rust_proto_aspect aspect on rust_library rule //cargo/vendor/bytes-1.0.1:bytes: Aspect implementation should return a struct, a list, or a provider instance, but got NoneType
ERROR: Analysis of target '//:server' failed; build aborted: Analysis of target '//cargo/vendor/bytes-1.0.1:bytes' failed

This is with the most recent rules_rust

**Comment by tschuett** [comment]
https://github.com/bazelbuild/rules_rust/archive/c21d89476dfc904bea0f399a63e285f6b71682cc.tar.gz

**Comment by UebelAndre** [comment]
Can you give an example workspace demonstrating this issue?
