### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by UebelAndre** [google/cargo-raze#387]
This is something that's been happening for more and more repos that I think would be a nice improvement. The change is pretty easy, if you rename the default branch in github, it'll update all PRs and notify users that the upstream of their forks have renamed their branches. The only thing needed after that is to ping Philipp Wollermann and get him to update CI (which takes just a second), he's pretty responsive when it comes to this specific request.

cc @acmcarther @dfreese

**Comment by acmcarther** [comment]
Updated on github and on buildkite.
