### ISSUE TITLE
BUG: flate2 (1.0.20) deps are incorrectly generated

### ISSUE THREAD

**Issue by palfrey** [google/cargo-raze#389]
Deps are generated as
```
    deps = [
        "@raze__cfg_if__1_0_0//:cfg_if",
        "@raze__crc32fast__1_2_1//:crc32fast",
        "@raze__libc__0_2_86//:libc",
        "@raze__miniz_oxide__0_4_4//:miniz_oxide",
    ] + selects.with_or({
        # cfg(all(target_arch = "wasm32", not(target_os = "emscripten")))
        (
            "@rules_rust//rust/platform:wasm32-unknown-unknown",
            "@rules_rust//rust/platform:wasm32-wasi",
        ): [
            "@raze__miniz_oxide__0_4_4//:miniz_oxide",
        ],
        "//conditions:default": [],
    }),
```

And you get
`
ERROR: /home/palfrey/.cache/bazel/_bazel_palfrey/1e69055091f05c565038b6edab4c56d2/external/raze__flate2__1_0_20/BUILD.bazel:77:13: Label '@raze__miniz_oxide__0_4_4//:miniz_oxide' is duplicated in the 'deps' attribute of rule 'flate2'
`

This is because in [the Cargo.toml](https://github.com/rust-lang/flate2-rs/blob/master/Cargo.toml) `miniz_oxide` is optional by default, except for in the wasm32 target when it's non-optional.

**Comment by warriorstar-orion** [comment]
For what it's worth, if you aren't targeting wasm, adding explicit target toolchains will cause raze to elide the select here, e.g.:

```toml
[workspace.metadata.raze]
targets = [
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]
```

**Comment by palfrey** [comment]
Confirmed that 8443486fa3eb61f3e0ce47c500b101b730e197c7 fixes my original issue
