### ISSUE TITLE
glob(["**/*.ext"])  for data_dependencies options

### ISSUE THREAD

**Issue by cristifalcas** [google/cargo-raze#432]
Accept pattern `glob(["**/*.ext"])`  for data_dependencies options.

Currently the option only allows arrays, but globs should be valid also.

This is needed (`glob(["**/*.der"])`) for ring, webpki and more.

**Comment by sayrer** [comment]
fwiw, you can use `data_attr` for these:

https://github.com/grafica/crustls/blob/cc_toolchain/Cargo.toml#L48

**Comment by cristifalcas** [comment]
Thank you!
