### ISSUE TITLE
rules_rust main branch currently doesn't work when "Using cargo-raze through Bazel"

### ISSUE THREAD

**Issue by jmesmon** [google/cargo-raze#453]
https://github.com/bazelbuild/rules_rust/issues/1026 notes the issue, which results in this error:

```
error loading package '@cargo_raze//impl': cannot load '@rules_rust//rust:rust.bzl': no such file and referenced by '@cargo_raze//tools:raze'
```

It appears that rules_rust has removed rust/rust.bzl in https://github.com/bazelbuild/rules_rust/pull/1002

**Comment by jmesmon** [comment]
Ah, this is to some degree my mistake: it looks like this has been fixed in cargo-raze, but no release including the fix has been cut, so I need to change my workspace to use a git rev rather than downloading a release of cargo-raze

**Comment by dfreese** [comment]
should be taken care of in v0.13.1.
