### ISSUE TITLE
Switch path code to Camino

### ISSUE THREAD

**Issue by sayrer** [google/cargo-raze#510]
I have some new features that use Camino, and I ended up replacing all of `cargo-raze`'s path code with Camino while hunting down bugs. Cargo requires UTF-8 paths anyway, as the Camino docs state, so I think it's a reasonable change. Ok to PR?

https://github.com/camino-rs/camino

**Comment by illicitonion** [comment]
Works for me - see also https://github.com/google/cargo-raze/issues/421 :)
