### ISSUE TITLE
Add build_file_path [raze.crate.version] override that supports providing a custom build file

### ISSUE THREAD

**Issue by acmcarther** [google/cargo-raze#58]
This is a pretty finicky proposition, all told. Dependencies are generally versioned and those versions can change due to non-local causes which would require manually updating the build file. One example of such a cause would be newly including a dependency that forces another dependency to downgrade.

The cleanest implementation of this would somehow allow the BUILD file author to refer to dependencies "at whatever version they would otherwise be" via an exported BZL file or something else.. An initial implementation could forego these niceties though.

cc: @mfarrugi

**Comment by mfarrugi** [comment]
Fwiw the two examples (backtrace-sys and libloading) have no dependencies, which should usually be the case for -sys crates. 

The only reason I've seen to override BUILD files completely has been to replace build.rs files that are building an inlined c library.

**Comment by acmcarther** [comment]
@mfarrugi: You referenced this issue in https://github.com/bazelbuild/rules_rust/pull/108. Are you just interested in replacing the BUILD file with some provided local file's contents?

Assuming that to be the case the change isn't onerous.

**Comment by acmcarther** [comment]
No, that's about it.

As a side note, it's going to be a bit of a hack as this bypasses the "planning" stage in the existing code structure (Metadata -> "Planned" Build -> "Rendered" Build).
