### ISSUE TITLE
Unable to use cargo-raze when vendored to subdirectory

### ISSUE THREAD

**Issue by photex** [google/cargo-raze#59]
Howdy!

I'm just trying to get started with this and explore this as a viable path from using cmake and cargo to using Bazel for a mixed C++ and Rust monorepo.

Right out of the gate though I'm running into troubles. I've run `cargo vendor -x vendor/crates`. I'm using the 'vendor' prefix because this is where we've already established our location for vendored C and C++ libraries.

I've created a WORKSPACE file set up for rust, I add the following to my Cargo.toml (which is the root of a cargo workspace):
```
[raze]
workspace_path = "//vendor/crates"
```

When I run `cargo raze` I get the following panic:
```
Loaded override settings: RazeSettings {
    workspace_path: "//vendor/crates",
    target: "x86_64-unknown-linux-gnu",
    crates: {},
    gen_workspace_prefix: "raze",
    genmode: Vendored
}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CargoError(Msg("failed to find ./vendor/vcpkg-0.2.4/. Either switch to \"Remote\" genmode, or run `cargo vendor -x` first."), State { next_error: None, backtrace: None })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

For some reason it doesn't appear to be using the crates subdirectory. This is a completely vanilla repo as far as bazel is concerned. I'm attempting to some of the less complicated rust targets building before stepping off into the C++ side.

**Comment by photex** [comment]
Ok I see at least part of the problem... it is expecting to find yet another folder specifically named 'vendor' under `//vendor/crates`. 

Is it possible to control this value?

**Comment by mfarrugi** [comment]
Currently the raze Cargo.toml needs to be in the directory corresponding to workspace_path, and the cargo vendor directory needs to be below it, so 

vendor/crates/Cargo.toml
vendor/crates/vendor

Is what you need.

**Comment by photex** [comment]
Thanks, this got me sorted and on to the next issues.
