### ISSUE TITLE
Derive builder does not build

### ISSUE THREAD

**Issue by acmcarther** [google/cargo-raze#6]
Needs markdown file as "include_str".

```
data = glob(["**/*"])
```
should do the trick (not sure the side effects though).

**Comment by mfarrugi** [comment]
Does adding it to `srcs` work (ie. changing the glob to "**/*")? Adding it to `data` will make it available under runfiles, which is a little undesirable.

**Comment by acmcarther** [comment]
Strangely enough, the above snippet *does* work. I suspect this is because the files are being accessed directly (instead of through runfiles, where they should be accessed from). Furthermore, non `rs` sources are not accepted in the `srcs` argument, though that could be changed.

**Comment by mfarrugi** [comment]
Oh I'm not saying data won't work, but the downside is that all sources become part of runfiles.

**Comment by acmcarther** [comment]
Ouch. Good point.

Perhaps `data` should be configurable via a `[raze]` option in the cargo toml? That would allow specifically bringing in `md` files for just this one crate.

**Comment by mfarrugi** [comment]
That will still leak it to runfiles, but it should be okay if it's only a
few files. The other option is to add a compile_data (non rust sources)
attribute, but that seems excessive and might encourage more bad behavior.
