### ISSUE TITLE
Issues installing the crate

### ISSUE THREAD

**Issue by SirWindfield** [google/cargo-raze#65]
I always get the following error when trying to install via `cargo install cargo-raze`:

```
error: failed to run custom build command for `openssl v0.9.24`                                                                                                                                  
process didn't exit successfully: `/tmp/cargo-install7rJjih/release/build/openssl-30a87315a59668e1/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/sven/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-raze v0.1.1`, intermediate artifacts can be found at `/tmp/cargo-install7rJjih`                                                                                  

Caused by:
  build failed
```

Not sure if that matters, but I have openssl installed. Strange thing is, I wanted to update cargo-raze, so I uninstalled it first. I could install it the first time without any problems. But now...

If you need any log files or other things, let me know.

**Comment by mfarrugi** [comment]
This is isolated to building the openssl crate, the openssl build.rs is not
finding your install.

I would try building that version from source then following up with
openssl crate.
