### ISSUE TITLE
Investigate using `cargo metadata` internally

### ISSUE THREAD

**Issue by acmcarther** [google/cargo-raze#7]
I wrote most of the integration before `cargo metadata` existed. I'm content with just continuting to use Cargo's internals in the event that `cargo metadata` is missing something needed, but if its possible to use it today, we probably should. 

Crosslinks:
https://github.com/rust-lang/cargo/issues/3815

**Comment by acmcarther** [comment]
I've rewritten the planner to use output from `cargo metadata`, but I'm blocked by a small feature request to Cargo. https://github.com/rust-lang/cargo/pull/5122 adds the extra data I need.

Once this change is in, the whole stack will get much more testable as it won't depend on weird internal state of Cargo objects.

**Comment by acmcarther** [comment]
cc https://github.com/rust-lang/cargo/issues/5583

I wasn't aware that these were outstanding issues. I'm currently working around lack of platform-specific details by performing dependency pruning:

https://github.com/google/cargo-raze/blob/2e4128f49ffaf7726002e30930db2aedbf205238/impl/src/planning.rs#L248-L257

(using dependency.target and comparing with the configured target).

https://github.com/google/cargo-raze/issues/53 tracks feature pruning (which is in an unclear state cargo-side as well).

**Comment by UebelAndre** [comment]
Is this investigation still open?
