### ISSUE TITLE
edition support

### ISSUE THREAD

**Issue by mfarrugi** [google/cargo-raze#79]
https://github.com/bazelbuild/rules_rust/issues/157

without rules_rust changes, raze can emit `--edition 2018` as needed

**Comment by acmcarther** [comment]
I think we need to take this information from the individual crates. We can't assume that an arbitrary crate is 2018 compatible.

**Comment by vitalyd** [comment]
@acmcarther (or anyone else, really), how involved is adding `--edition` support? Naively, I'd imagine this shouldn't be too bad: propagate `cargo` manifest's `edition` value, if present, to the generated `BUILD` file.  I suppose while https://github.com/bazelbuild/rules_rust/issues/157 is still open, `raze` can add the edition as a `rustc_flags` argument.

Is that accurate? If so, any idea when the support might be added? Sorry, I'm not entirely sure how this project is maintained.

Thanks

**Comment by acmcarther** [comment]
Sorry for the delay on this. I haven't been able to set aside much time recently to hash this out.

[Edition is a new field in SerializedTarget](https://github.com/rust-lang/cargo/blob/master/src/cargo/core/manifest.rs#L263-L275). This field is supposed to be one to one with our [`metadata::Target`](https://github.com/google/cargo-raze/blob/master/impl/src/metadata.rs#L114-L127) .

This field ought to be automatically populated by the `cargo metadata` codepath (CargoSubcommandMetadataFetcher), but will need to be added to the internals-using codepath (CargoInternalsMetadataFetcher): the target section is here:
https://github.com/google/cargo-raze/blob/1a793666a89a62ead2aa0c2ea26fe8b33aacefbd/impl/src/metadata.rs#L304-L310

... I would have liked to add where this information is available in the resolved package, but I don't have any more time this morning to look into this. 


If you're interested in implementing it, I would be very happy to review a pull request. Else, you're unfortunately beholden to my flakiness. I'll make a concerted effort to work on this item soon given its relevance in the recently released 1.31.0

**Comment by mfarrugi** [comment]
And with https://github.com/pacman82/atoi-rs/commit/58633976e59c2359b1c576069c2ff31ebc505a26#diff-80398c5faae3c069e4e6aa2ed11b28c0 I've run into this as a problem :)

For now it sufficed to pin the dep to the previous version.
