### ISSUE TITLE
Not all binaries have a library to depend on (can't build ripgrep)

### ISSUE THREAD

**Issue by mfarrugi** [google/cargo-raze#83]
Added

```
ripgrep = "0.10.0"

...

[raze.crates.ripgrep.'0.10.0']
extra_aliased_targets = [
    "cargo_bin_rg"
]
```
to my Cargo.toml, but get an error when trying to build `:cargo_bin_rg` because it depends on a library target that doesn't exist.

---

https://github.com/google/cargo-raze/blob/d98b6818c04b5c36ef0b6523bd224e6f52d113b4/impl/src/templates/partials/rust_binary.template#L10-L11

This ought to be a little smarter.. any suggestions?

**Comment by acmcarther** [comment]
I've got a short wip fix for this [here](https://github.com/google/cargo-raze/compare/acm-fix-bin-planning) that just adds a bool to check if the crate has a lib with the same name, but I want to make some other quick changes to make testing features at the crate level easier.

I should have a PR up for this in the next day or two.

**Comment by acmcarther** [comment]
Seems I've made a bad assumption in that implementation. I assumed that lib targets that don't share the name of the crate won't be automatically linked. This actually isn't correct in practice. Instead, there is only ever one "lib" target in the target set, and that target is automatically linked to some of the other targets (binary for sure, build script definitely not).

.... And, my sleuthing results:

[The place in cargo where things that aren't buildscript or lib get the buildscript and library as a dep](
https://github.com/rust-lang/cargo/blob/d4af22356a4836bac3b1c5de9115eec348d97628/src/cargo/core/compiler/context/unit_dependencies.rs#L187-L202)
```rust
    // If this target is a build script, then what we've collected so far is
    // all we need. If this isn't a build script, then it depends on the
    // build script if there is one.
    if unit.target.is_custom_build() {
        return Ok(ret);
    }
    ret.extend(dep_build_script(unit, bcx));

    // If this target is a binary, test, example, etc, then it depends on
    // the library of the same package. The call to `resolve.deps` above
    // didn't include `pkg` in the return values, so we need to special case
    // it here and see if we need to push `(pkg, pkg_lib_target)`.
    if unit.target.is_lib() && unit.mode != CompileMode::Doctest {
        return Ok(ret);
    }
    ret.extend(maybe_lib(unit, bcx, unit_for));
```

[The place in cargo where rustdoc binaries get their library as a dep automatically](
https://github.com/rust-lang/cargo/blob/d4af22356a4836bac3b1c5de9115eec348d97628/src/cargo/core/compiler/context/unit_dependencies.rs#L324-L327)
```rust
    // If we document a binary, we need the library available
    if unit.target.is_bin() {
        ret.extend(maybe_lib(unit, bcx, UnitFor::new_normal()));
    }
```

[The "maybe_lib" implementation](
https://github.com/rust-lang/cargo/blob/d4af22356a4836bac3b1c5de9115eec348d97628/src/cargo/core/compiler/context/unit_dependencies.rs#L331-L341)
```rust
fn maybe_lib<'a>(
    unit: &Unit<'a>,
    bcx: &BuildContext<'_, '_>,
    unit_for: UnitFor,
) -> Option<(Unit<'a>, UnitFor)> {
    unit.pkg.targets().iter().find(|t| t.linkable()).map(|t| {
        let mode = check_or_build_mode(unit.mode, t);
        let unit = new_unit(bcx, unit.pkg, t, unit_for, unit.kind.for_target(t), mode);
        (unit, unit_for)
    })
```

Seems they link "anything linkable" to binaries. [That's only true for libs](https://github.com/rust-lang/cargo/blob/afef1f04de18197d45e75c7a191c9cb072ba3438/src/cargo/core/manifest.rs#L786-L791), but may not stay that way forever

```rust
    pub fn linkable(&self) -> bool {
        match self.kind {
            TargetKind::Lib(ref kinds) => kinds.iter().any(|k| k.linkable()),
            _ => false,
        }
    }
```

I'll update my implementation in the last comment to provide crate-level metadata for all "linkable" targets and add deps for those automatically.
